/*
 * Web UI - Embedded gzipped SPA file accessors
 */

#include "web_ui.h"

/* Embedded gzipped file symbols (generated by linker)
 * Note: symbols use underscores for dots and slashes in filename path */
extern const uint8_t _binary_index_html_gz_start[];
extern const uint8_t _binary_index_html_gz_end[];
extern const uint8_t _binary_index_js_gz_start[];
extern const uint8_t _binary_index_js_gz_end[];
extern const uint8_t _binary_index_css_gz_start[];
extern const uint8_t _binary_index_css_gz_end[];

const uint8_t* web_ui_get_index_html_gz(size_t *len)
{
    *len = _binary_index_html_gz_end - _binary_index_html_gz_start;
    return _binary_index_html_gz_start;
}

const uint8_t* web_ui_get_index_js_gz(size_t *len)
{
    *len = _binary_index_js_gz_end - _binary_index_js_gz_start;
    return _binary_index_js_gz_start;
}

const uint8_t* web_ui_get_index_css_gz(size_t *len)
{
    *len = _binary_index_css_gz_end - _binary_index_css_gz_start;
    return _binary_index_css_gz_start;
}
